### ISSUE TITLE
syntax error in docker-compose config

### ISSUE THREAD

**Issue by phtppp** [TrueOsiris/docker-vrising#11]
There should only be one "/udp" per line, so instead of

    ports:
      - '9876/udp:9876/udp'
      - '9877/udp:9877/udp'

it should look like

    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'

EDIT: I am referencing the example in README.md

**Comment by TrueOsiris** [comment]
Confirmed. Error was added by merge.
