### ISSUE TITLE
Timezone issue?

### ISSUE THREAD

**Issue by ilusionbr** [TrueOsiris/docker-vrising#18]
Hello,  any way to configure Timezone? My TZ is UTC -3 but the server keeps working on UTC so i cant configure the Raid for the time i want. 
What im missing?

**Comment by TrueOsiris** [comment]
I think it's my bad here. In other containers I used a more elaborate method to fix the timezone.
I'll update.

**Comment by ilusionbr** [comment]
Haha i almost melted my brain out here trying to figure out what i was missing.
I'll wait for you update then, thanks man. You image is the only one that worked perfectly for me.

**Comment by TrueOsiris** [comment]
ok, pull the latest version please & tell me if the TZ is ok now.

**Comment by ilusionbr** [comment]
Its working. Can we start use? Or you gonna change something else?
Thanks man i appreciate your work.
