### ISSUE TITLE
Server not visible in server browser

### ISSUE THREAD

**Issue by StephanBis** [TrueOsiris/docker-vrising#2]
It works like a charm, thank you! Direct connect is working, however the server is not visible in the game's server browser. (direct connect: xx.xx.xx.xx:27015)
I've forwarded 27015 to 9876 and 27016 to 9877 in Docker settings, is this correct? Both ports are opened in the firewall aswell.

**Comment by TrueOsiris** [comment]
If you forward ports, you can indeed only use direct connect.
If you want to see the server in the server list, you'll need to change the ports in the ServerHostSettings.json file to 27015 and 27016.
And then just expose ports 
-p 27015:27015
-p 27016:27016
