### ISSUE TITLE
Can`t login with adminauth

### ISSUE THREAD

**Issue by ilusionbr** [TrueOsiris/docker-vrising#21]
Hello TrueOsiris. Im getting a strange message "Authentication failed! You have been awared with: -5dkp" when i try to login with adminauth on console.
It was working before, but now im getting this message.
You know how to fix this?

**Comment by ich777** [comment]
@ilusionbr please see this issue here, maybe it solves your issue too: [Click](https://github.com/StunlockStudios/vrising-dedicated-server-instructions/issues/26) 

@TrueOsiris I don‘t know if you are aware of this.

**Comment by ilusionbr** [comment]
@ich777 Yeah, it solved my problem, thanks a lot brother. Also, @TrueOsiris, the adminlist and banlist in Settings in Settings on (data) folder doesn't work. Only in server folder.
