### ISSUE TITLE
Cannot use my own build dockerfile

### ISSUE THREAD

**Issue by johnhelt** [TrueOsiris/docker-vrising#22]
First of all, thank you for sharing this! I am able to run the docker-compose file just fine out of the box (after adjusing the location of my server config files etc.).

Now, I wanted to make my own docker image using the provided Dockerfile. The build finishes fine, however, when I run the docker-compose with the new (local) image, wine somehow seems to crash, and the server hangs. Is there some build arguments I need to apply, which are not described in the readme file?

Sincerely, John

**Comment by TrueOsiris** [comment]
Nope, mate. Everything you see is inhere. fork it, then on your dockerhost where you build images.
I use https://github.com/TrueOsiris/git to build everything up to my images. Use the credentials file as described to set the correct git & docker settings, and created that integration in git settings as described.

connect to it with `docker exec -it git /bin/bash`
Inthere do `git clone https://github.com/yourgitrepo/vrising` which I assume you forked.
I'm going to assume that you created a docker repo with exactly the same name.
further:
```
cd vrising
gitpush "somecomment" main && dockerpush vrising:lastest
```
you can just read what is in the gitpush & dockerpush commands. They're just bashscripts.

Also, the vrising server, let it build for a while. the logs outputs tons of errors anyway! It can take a decent amount of time (15 mins) on a slower system.

**Comment by johnhelt** [comment]
Thanks for your reply. I did what you said, and waited, while ignoring the errors thrown, and after a while the server did start up, and I was able to connect. I guess my little NUC (J3160 with 4gb ram), is just on the low end side for running the server.

**Comment by TrueOsiris** [comment]
Once it runs, it should be fine, depending on how much of that ram is available.
