### ISSUE TITLE
Wine cannot find server.exe

### ISSUE THREAD

**Issue by stephenclau** [TrueOsiris/docker-vrising#27]
Updating V-Rising Dedicated Server files...
vrising    |
vrising    | /root/.local/share/Steam/steamcmd/steamcmd.sh: line 38:    31 Killed                  $DEBUGGER "$STEAMEXE" "$@"
vrising    | steam_appid:
vrising    |
vrising    | cat: /mnt/vrising/server/steam_appid.txt: No such file or directory
vrising    | Starting V Rising Dedicated Server with name LosHermanos
vrising    | Trying to remove /tmp/.X0-lock
vrising    |
vrising    | Starting Xvfb
vrising    | Launching wine64 V Rising
vrising    |
vrising    | wine: cannot find L"/mnt/vrising/server/VRisingServer.exe"
vrising    | /usr/bin/tail: cannot open '/mnt/vrising/persistentdata/VRisingServer.log' for reading: No such file or directory
vrising    | /usr/bin/tail: no files remaining

**Comment by TrueOsiris** [comment]
Sorry about the late reply, but I'm going to need much more information.

**Comment by xrobert35** [comment]
see #30 it seem to be the same,

hop it help
