### ISSUE TITLE
[Resolved] Server won't start

### ISSUE THREAD

**Issue by xrobert35** [TrueOsiris/docker-vrising#30]
Hello,

i'm trying to start the server using the docker-compose.yml you provided in the readme and i've this error : 

I'm user docker on a fedora coreos and I have this error.  (it's look like there is a problem with this steam installation ?) 
```
Success! App '1829350' fully installed.
cat: /mnt/vrising/server/steam_appid.txt: No such file or directory
steam_appid: 

/mnt/vrising/persistentdata/Settings/ServerGameSettings.json not found. Copying default file.
cp: cannot stat '/mnt/vrising/server/VRisingServer_Data/StreamingAssets/Settings/ServerGameSettings.json': No such file or directory
/mnt/vrising/persistentdata/Settings/ServerHostSettings.json not found. Copying default file.
cp: cannot stat '/mnt/vrising/server/VRisingServer_Data/StreamingAssets/Settings/ServerHostSettings.json': No such file or directory
Starting V Rising Dedicated Server with name vrisingDocker

Trying to remove /tmp/.X0-lock
rm: cannot remove '/tmp/.X0-lock': No such file or directory

Starting Xvfb
Launching wine64 V Rising

wine: created the configuration directory '/root/.wine'
wine: cannot find L"/mnt/vrising/server/VRisingServer.exe"
/usr/bin/tail: cannot open '/mnt/vrising/persistentdata/VRisingServer.log' for reading: No such file or directory
```

I've tried on docker windows also and there were files on the mounted **server** and **data**  but it also failed with  this error

```
0024:err:module:LdrInitializeThunk "UnityPlayer.dll" failed to initialize, aborting
0024:err:module:LdrInitializeThunk Initializing dlls for L"Z:\\mnt\\vrising\\server\\VRisingServer.exe" failed, status c0000005
```

But here my folder are empty.

So I dunno if it's linked to the docker version or something else but I needed to **remove the volumes directive** and the server was starting. There is not really "start ok" log but it's up and I can connect. 

So now I will just copy the  "/mnt/vrising/persistentdata" on my host disk using docker cp, add back the volume - './data:/mnt/vrising/persistentdata:rw'  and it will be fine

I can do the same for ./server:/mnt/vrising/server:rw  but do we really need to mount the ''./server:/mnt/vrising/server:rw''  ?

Hop it help someone,

Thanks for the job @TrueOsiris,

Xavier

**Comment by TrueOsiris** [comment]
To be honest, I merged the docker-compose.yml from another contributor.
I'll verify.
