### ISSUE TITLE
How i change the publish servername?

### ISSUE THREAD

**Issue by puera** [TrueOsiris/docker-vrising#31]
Hello,

How i can change the  publish servername after i start the container (docker-compose) with variables? It's possible? 
I know the variable servername overwrite the config on ServerHostSettings.json

If i recreate the container again i will lose the volumes created before?

Thank you in advance

**Comment by TrueOsiris** [comment]
`-e SERVERNAME="trueosiris-V" `

You can certainly alter this value. 
No, you will not lose them volumes created.
So, in short, just stop & remove the container, then run it again with different environment variables but with the same volumes.

PS: Lots of people use Portainer or something equivalent to manage their other containers.
