### ISSUE TITLE
Can't start, lot's of error

### ISSUE THREAD

**Issue by dreep** [TrueOsiris/docker-vrising#32]
Hi,

I try to create a server for vrising but i have these errors : 

wine: created the configuration directory '/root/.wine'
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0048:err:ole:start_rpcss Failed to open RpcSs service
0040:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
Could not find Wine Gecko. HTML rendering will be disabled.
Could not find Wine Gecko. HTML rendering will be disabled.
002c:fixme:event:wait_for_withdrawn_state window 0x2004e/c00001 wait timed out
wine: configuration in L"/root/.wine" has been updated.
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
015c:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007FFFFE53FE10
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007F7AFE7F2820, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:ntdll:EtwEventRegister ({f72b578f-cae9-556a-01dc-b94f14b3cbd9}, 000000013F001100, 000000013F05B018, 000000013F05B038) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504BE, 13) stub
0024:fixme:ntdll:EtwEventRegister ({66f0a0b9-f747-5080-bdb9-4974c990ecd2}, 000000013F001100, 000000013F05B050, 000000013F05B070) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504DC, 19) stub
0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0180:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
0180:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007F7A709D58D0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0180:fixme:wbemprox:client_security_Release 00000002419BFD50
0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0180:fixme:wbemprox:enum_class_object_Next timeout not supported
0094:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0094:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
016c:fixme:iphlpapi:NotifyAddrChange (Handle 0x7f7a46040410, overlapped 0x7f7a46040418): stub
0024:fixme:ntdll:EtwEventRegister ({b77d8a36-ef0c-4976-8d22-08f986f56cfb}, 0000000138879800, 00000001393101A0, 00000001393AFA88) stub.
018c:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007F7AFC49FE10
dbus[111]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00007FC16BC06A7C (thread 0094), starting debugger...
016c:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
016c:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0168:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x7f7afcb1fa18.
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007F7A713D7600, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:ntdll:EtwEventRegister ({35167f8e-49b2-4b96-ab86-435b59336b5e}, 00007F7B4F0CEA00, 0000000000003D93, 00007F7AFD421100) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00007F7AFDD79BF0, 65) stub

Someone could tell me what is my error ?

**Comment by TrueOsiris** [comment]
half of the errors, if not more, are the normal output.
What platform is your docker running on?
What ports did you open? Did you open/forward them properly on your firewall?

**Comment by jobsidi** [comment]
I have the same errors too. Seems alsa is sound think and others arent critical ones.
But anyway i cannot connect to the server in lan. 
Client 0.5.42584
Server debian 11.
Ports are opened more then in container
TCP: 27015, 27036
UDP: 27015-27016, 27031-27036
0.0.0.0:9876  9876/udp
0.0.0.0:9877  9877/udp
ports listeners are ok, i checked it.
also i tried to change it to host instead of bridge without any results. Any ideas?

**Comment by dreep** [comment]
> What platform is your docker running on?
Docker on Portainer from Openmediavault os
> What ports did you open? Did you open/forward them properly on your firewall?
I tried with 9876 and 9877
And after with 27015 and 27016
Solareon image work, but i would like to configure and use yours...

**Comment by dreep** [comment]
What works actually :
`#https://hub.docker.com/r/solareon/vrising-svr
version: "3"
services: 
  vrising:
    container_name: vrising-server
    image: solareon/vrising-svr:latest
    volumes: 
      - /docker_data/vrising-server/server:/mnt/vrising/server
      - /docker_data/vrising-server/persistentdata:/mnt/vrising/persistentdata
    environment:
      - TZ=Europe/Paris
      - "SERVER_NAME=/////////"
      - "SERVER_DESCRIPTION=A game with friends"
      - GAME_PORT=27015
      - QUERY_PORT=27016
      - MAX_USERS=4
      - MAX_ADMIN=2
      - SERVER_FPS=30
      - "SAVE_NAME=/////////"
      - "SERVER_PASS=//////////"
      - STEAM_LIST=true
      - AUTOSAVE_NUM=5
      - AUTOSAVE_INT=300
      - "GAME_PRESET=EasyPvE"
      - RCON_ENABLE=true
      - RCON_PORT=25575
      - "RCON_PASSWORD=/////////"
    ports: 
      - "27015:27015/udp"
      - "27016:27016/udp"
      - "25575:25575/tcp"`

**Comment by TrueOsiris** [comment]
Although this seems only an issue for some people, I'm going to leave this open as a reference, so they can be helped by https://hub.docker.com/r/solareon/vrising-svr

**Comment by Dalenir** [comment]
Hello. 
Somehow installing jq fixed this bug for me.
![image](https://github.com/TrueOsiris/docker-vrising/assets/60537405/a40c8d87-0c88-454d-aa62-0a534f222f9f)

**Comment by TrueOsiris** [comment]
closing. jq was added to the image
