### ISSUE TITLE
server with password not visible in game server list

### ISSUE THREAD

**Issue by ocangelo** [TrueOsiris/docker-vrising#33]
just trying to set this up for the first time, with all default settings i can find my server in the list and join it without problems.
as soon as i add a password to the json i can't find my server anymore on the server list.
running on a synology DS923+

**Comment by ocangelo** [comment]
looks like if i add my password to:

./vrising/server/VRisingServer_Data/StreamingAssets/Settings/ServerHostSettings.json

and remove the override from

./vrising/persistentdata/Settings/ServerHostSettings.json

i can see the server and connect to it without problems

**Comment by TrueOsiris** [comment]
Can anyone confirm this issue? I'm not able to reproduce this.

**Comment by AurimasNav** [comment]
might be similar problem https://github.com/TrueOsiris/docker-vrising/issues/47#issuecomment-2101052579

**Comment by TrueOsiris** [comment]
solved with changed settings in server config. Documented in readme.md
