### ISSUE TITLE
Gloomrot Update

### ISSUE THREAD

**Issue by pustekuchen91** [TrueOsiris/docker-vrising#34]
Is this container compatible with the latest gloomrot update?

**Comment by AlexPerni** [comment]
Currently no. 
Before the update, I was able to connect easily. Now it does not work. 
There is a pull request though. Perhaps that will solve it.

**Comment by pustekuchen91** [comment]
I cant agree. I first started the server on my NAS, which makes problems so far. But starting the container locally, i can connect flawless. So my question about compatibilty is answered.
