### ISSUE TITLE
got always denied even with correct password

### ISSUE THREAD

**Issue by dsmanneke** [TrueOsiris/docker-vrising#35]
got always denied even with correct password
`NetConnection '{Steam xxxxxxx}' connection was denied. Message: 'Incorrect Password!' Version: 4 PlatformId: xxxxxxx`

if we remove the password, we see the following in the log:
```
[Server] Shutting down Asynchronous Streaming
SteamPlatformSystem - BeginAuthSession for SteamID: xxxxx Result: k_EBeginAuthSessionResultOK
NetEndPoint '{Steam xxxxx }' reconnect was approved. approvedUserIndex: 0 HasLocalCharacter: True Hail Message Size: 271 Version: 4 PlatformId: xxxxx UserIndex: 1 ShouldCreateCharacter: False IsAdmin: False Length: 271
SteamPlatformSystem - BeginAuthSession for SteamID: xxxx Result: k_EBeginAuthSessionResultOK
NetEndPoint '{Steam xxxx }' reconnect was approved. approvedUserIndex: 1 HasLocalCharacter: True Hail Message Size: 271 Version: 4 PlatformId: xxxxx UserIndex: 0 ShouldCreateCharacter: False IsAdmin: False Length: 271
[512:524:20230519,150943.767:ERROR filesystem_win.cc:129] GetFileAttributes C:\users\root\AppData\LocalLow\Stunlock Studios\VRisingServer\backtrace\crashpad\attachments\9eeb3b91-afa0-4d22-98dc-9d2575f0e46e: File not found. (2)
[512:524:20230519,150943.837:WARNING minidump_to_upload_parameters.cc:32] duplicate key guid, discarding value 25b148ca3c37dd34a8eaefdfe2a9c465ecc42366
020c:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0234:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000021FD70
[512:524:20230519,150945.680:ERROR http_transport_win.cc:388] HTTP status 429
0204:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000021FD70
0098:err:rpc:I_RpcReceive we got fault packet with status 0x1c010003
```

on the game itself, we see only a connection error

**Comment by sjdodge123** [comment]
I think this is similar to what I'm seeing as well

**Comment by nickktoast** [comment]
You probably need to install the winbind package for wine. Maybe update the docker file and build a new image with it included. 

https://forum.winehq.org/viewtopic.php?t=33023

**Comment by TrueOsiris** [comment]
@sjdodge123 @nickktoast @dsmanneke I've added winbind as suggested. Can you confirm this solves the issue? I'm not able to reproduce it myself

**Comment by dsmanneke** [comment]
issue still persists
Here you have a new complete log:
`-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
OK
"@sSteamCmdForcePlatformType" = "windows"
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 55.60 (24381288 / 43850712)
Success! App '1829350' fully installed.
steam_appid: 1604030
 
AVX or AVX2 not supported; Check if unsupported VRisingServer_Data/Plugins/x86_64/lib_burst_generated.dll exists
Changing VRisingServer_Data/Plugins/x86_64/lib_burst_generated.dll as attempt to fix issues...
 
Starting V Rising Dedicated Server with name VrisingSvens
Trying to remove /tmp/.X0-lock
rm: cannot remove '/tmp/.X0-lock': No such file or directory
 
Starting Xvfb
Launching wine64 V Rising
 
wine: created the configuration directory '/root/.wine'
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0048:err:ole:start_rpcss Failed to open RpcSs service
0040:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
Could not find Wine Gecko. HTML rendering will be disabled.
Could not find Wine Gecko. HTML rendering will be disabled.
002c:fixme:event:wait_for_withdrawn_state window 0x30022/c00001 wait timed out
wine: configuration in L"/root/.wine" has been updated.
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
01a0:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007F313AC2FE10
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007F305CB0EC50, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
01b0:fixme:iphlpapi:NotifyAddrChange (Handle 0x7f3138c10018, overlapped 0x7f3138c10020): stub
01c8:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
01c8:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007F305D74C580, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
01c8:fixme:wbemprox:client_security_Release 00000002419BFD50
0090:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0090:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
01c8:fixme:wbemprox:enum_class_object_Next timeout not supported
0090:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0090:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0090:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0090:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0024:fixme:ntdll:EtwEventRegister ({b77d8a36-ef0c-4976-8d22-08f986f56cfb}, 0000000138960E70, 00000001393DAEE0, 000000013948E808) stub.
01d8:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007F2FF99CFE10
dbus[125]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00007F1BE4618A7C (thread 0090), starting debugger...
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01ac:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x6755f9f8.
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01b0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007F305E3F9E90, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:file:NtLockFile I/O completion on lock not implemented yet
0204:fixme:file:NtLockFile I/O completion on lock not implemented yet
0204:fixme:process:SetProcessShutdownParameters (00000100, 00000001): partial stub.`
