### ISSUE TITLE
Connecting to this container running on docker desktop

### ISSUE THREAD

**Issue by BarnacleBob** [TrueOsiris/docker-vrising#36]
I was easily able to get this container running in docker desktop (thanks dev!) but i cannot for the life of me figure out how to connect.  the server was started via the example compose yaml, but i have no idea what to specify in the direct connect.  i tried the containers bridge ip, localhost, my bridge ip, i just have no idea what it should be.

Does anyone else know how to connect from the game?

**Comment by AlexPerni** [comment]
Since the Gloomrot update, there is an error happening and the server does not boot up correctly. The container image needs an update. Probably just wait and hope that trueosiris will fix it 😢

**Comment by pustekuchen91** [comment]
I just connected with my local IP-Adress. Maybe check the portforwarding.

**Comment by BarnacleBob** [comment]
Thanks to the hint that it was a local ip i was able to figure this out.  Docker desktop with wsl2 creates a new interface.  In docker desktop you can see what network its on by going to settings -> resources -> network.  Mine was 192.168.65.0/24 and so my local ip 192.168.65.1 got me connected from the game.
