### ISSUE TITLE
Can't apply server settings, potential volume definition issues

### ISSUE THREAD

**Issue by TheDenast** [TrueOsiris/docker-vrising#39]
First, of all, extremely sorry, I'm a Docker noob and quite possibly I messed up somewhere. 
I'm using docker-compose.yml in order to initialize the container and I've edited the volumes as the following:
```
    volumes:                                                                                      
      - './server:/home/denast/Docker/Vrising/server:rw'                                          
      - './data:/home/denast/Docker/Vrising/persistentdata:rw'
```
Where `/home/denast/Docker/Vrising/server` and `/home/denast/Docker/Vrising/persistentdata` are directories I've manually created on my machine. 

Container has launched fine and I can connect to the server no problem, however it proceeded to ignore `pesistentdata` path and created a  `/home/denast/Docker/Vrising/data` directory. I've then attempted to edit server settings in that `data` directory as suggested by readme, but they don't seem to get applied after restart. Particularly, server does not prompt the password that I've set in `ServerHostSettings.json`.

I've restarted the container with both `sudo docker restart vrising` and `sudo docker-compose up -d`, nothing happens. I've also edited `docker-compose.yml` to correct new "data" location to `Vrising/data`, no difference.

If I look at the process description with `bpytop`, it has the following flag:  `-persistentDataPath /mnt/vrising/persistentdata`, directory `/mnt/vrising/` does not exist on my machine.

Spent many hours tinkering and got nowhere, any ideas? I'll appreciate any help!

**Comment by Metalrasputian** [comment]
You've got your binds backwards I believe.

Should be:

`volumes:
  - '/home/denast/Docker/Vrising/server:/mnt/vrising/server:rw'
  - '/home/denast/Docker/Vrising/persistentdata:/mnt/vrising/persistentdata:rw'`
  
The first (left) side of the colon is your HOST (the system running docker) directory you want to mount to. The second (right) side is where you want to mount it onto your CONTAINER (the docker container running on the host)

**Comment by TheDenast** [comment]
This worked! Many thanks, marking issue as resolved
