### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by mattiasghodsian** [TrueOsiris/docker-vrising#4]
Running this on a ubuntu server and can't seem to connect to the server localy, also found a few issues in the output

```
vrising    | Starting V Rising Dedicated Server with name vrisingDocker                                                                          
vrising    | SteamAppId set to                                                                                                                   
vrising    | Starting mono ...                                                                                                                   
vrising    |                                                                                                                                     
vrising    | 0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION                                                 
vrising    | ALSA lib confmisc.c:855:(parse_card) cannot find card '0'                                                                           
vrising    | ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory                   
vrising    | ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings                                                                  
vrising    | ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory                      
vrising    | ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name                                                                     
vrising    | ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                       
vrising    | ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory                                                  
vrising    | ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default                                                                     
vrising    | ALSA lib confmisc.c:855:(parse_card) cannot find card '0'                                                                           
vrising    | ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory                   
vrising    | ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings                                                                  
vrising    | ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory                      
vrising    | ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name                                                                     
vrising    | ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                       
vrising    | ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory                                                  
vrising    | ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default                                                                     
vrising    | 0188:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007FFFFF0CFE10                                       
vrising    | 0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007FEC88160200, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
vrising    | 0024:fixme:wbemprox:client_security_Release 00000002419BFD50                                                                        
vrising    | 0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030                                                   
vrising    | 0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030                                                   
vrising    | 0024:fixme:keyboard:X11DRV_GetKeyboardLayout couldn't return keyboard layout for thread 005c                                        
vrising    | 0024:fixme:keyboard:X11DRV_GetKeyboardLayout couldn't return keyboard layout for thread 005c                                        
vrising    | 0024:fixme:ntdll:EtwEventRegister ({f72b578f-cae9-556a-01dc-b94f14b3cbd9}, 000000013F001100, 000000013F05B018, 000000013F05B038) stu
b.                                                                                                                                               
vrising    | 0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504BE, 13) stub                                                    
vrising    | 0024:fixme:ntdll:EtwEventRegister ({66f0a0b9-f747-5080-bdb9-4974c990ecd2}, 000000013F001100, 000000013F05B050, 000000013F05B070) stu
b.                                                                                                                                               
vrising    | 0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504DC, 19) stub                                                    
vrising    | 0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usu
ally, you can find it in the winbind package of your distribution.                                                                               
vrising    | 01ac:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags                                                                    
vrising    | 01ac:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007FEC88C31CD0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
vrising    | 01ac:fixme:wbemprox:client_security_Release 00000002419BFD50  
vrising    | 01ac:fixme:wbemprox:client_security_Release 00000002419BFD50
vrising    | 0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
vrising    | 0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
vrising    | 01ac:fixme:wbemprox:enum_class_object_Next timeout not supported
vrising    | 0060:fixme:mountmgr:query_property Faking StorageDeviceProperty data
vrising    | 0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
vrising    | 0060:fixme:mountmgr:query_property Faking StorageDeviceProperty data
vrising    | 0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
vrising    | 0198:fixme:iphlpapi:NotifyAddrChange (Handle 0x7fec3e040410, overlapped 0x7fec3e040418): stub
vrising    | 0024:fixme:ntdll:EtwEventRegister ({b77d8a36-ef0c-4976-8d22-08f986f56cfb}, 0000000138879800, 00000001393101A0, 00000001393AFA88) stu
b.
vrising    | 01b8:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007FECF4A9FE10
vrising    | 0194:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x7fecf4defa18.
vrising    | dbus[50]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../
../../dbus/dbus-connection.c line 3544.
vrising    | This is normally a bug in some application using the D-Bus library.
vrising    | 
vrising    |   D-Bus not built with -rdynamic so unable to print a backtrace
vrising    | wine: Assertion failed at address 00007F799A71DA7C (thread 0060), starting debugger...
vrising    | 0198:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
vrising    | 0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007FEC895D0590, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
vrising    | 0024:fixme:wbemprox:client_security_Release 00000002419BFD50
vrising    | 0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
vrising    | 0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
vrising    | 0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
vrising    | 0024:fixme:ntdll:EtwEventRegister ({35167f8e-49b2-4b96-ab86-435b59336b5e}, 00007FED4D3236D0, 0000000000003D03, 00007FECF53CF870) stu
b.
vrising    | 0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00007FEBEDDEE100, 65) stub
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by TrueOsiris** [comment]
Can you state your processor type, host os & docker version, please?
That errordump from starting the dedicated server is almost similar to mine.

**Comment by mattiasghodsian** [comment]
> Can you state your processor type, host os & docker version, please? That errordump from starting the dedicated server is almost similar to mine.

I ran `docker-compose up -d`
```
version: '3.3'
services:
  vrising:
    build: .
    container_name: vrising
    network_mode: bridge
    environment:
      - TZ=Europe/Paris
      - SERVERNAME=vrisingDocker
    volumes:
      - './server:/mnt/vrising/server:rw'
      - './data:/mnt/vrising/persistentdata:rw'
    ports:
      - '9876:9876'
      - '9877:9877'
```

## Host
OS: Ubuntu 20.04.4 LTS
Kernel: 5.4.0.-109-generic
RAM: 64 GB
CPU: 2x Intel Xeon E5-2637 v3 3.7 GHz
GPU: NVIDIA Quadro K2200

## Docker
Version: 20.10.14

## Docker-compose
Version: 1.29.1

**Comment by Chapapa1** [comment]
i have this problem now aswell :)
host: amd ryzen 5 5600g, Linux 5.15 12-1-pve (proxmox7.1-8), LXC Container (Ubuntu 22.04)
Docker: 20.10.16

**Comment by TrueOsiris** [comment]
^CGracefully stopping... (press Ctrl+C again to force) 

-> this is a manual action?

coz this is the normal output:

`0164:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007FFFFE64FE10
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 0000145E1D537A90, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:ntdll:EtwEventRegister ({f72b578f-cae9-556a-01dc-b94f14b3cbd9}, 000000013F001100, 000000013F05B018, 000000013F05B038) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504BE, 13) stub
0024:fixme:ntdll:EtwEventRegister ({66f0a0b9-f747-5080-bdb9-4974c990ecd2}, 000000013F001100, 000000013F05B050, 000000013F05B070) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504DC, 19) stub
0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0188:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
0188:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 0000145D60BFDB50, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0188:fixme:wbemprox:client_security_Release 00000002419BFD50
0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0188:fixme:wbemprox:enum_class_object_Next timeout not supported
0094:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0174:fixme:iphlpapi:NotifyAddrChange (Handle 0x145d5cbe0410, overlapped 0x145d5cbe0418): stub
0094:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0024:fixme:ntdll:EtwEventRegister ({b77d8a36-ef0c-4976-8d22-08f986f56cfb}, 0000000138879800, 00000001393101A0, 00000001393AFA88) stub.
0194:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 0000145D5C6FFE10
dbus[95]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00001540AE492A7C (thread 0094), starting debugger...
0174:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0174:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0170:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x145d5cb5fa18.
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 0000145D615B1030, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:ntdll:EtwEventRegister ({35167f8e-49b2-4b96-ab86-435b59336b5e}, 0000145E24B736D0, 0000000000003D03, 0000145D3463FAA0) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000145CE0AA7020, 65) stub
`

**Comment by Chapapa1** [comment]
Ah, it works, same errors but i can connect now.

**Comment by mattiasghodsian** [comment]
> ^CGracefully stopping... (press Ctrl+C again to force)
> 
> -> this is a manual action? are u running it detached? `docker run -d`
> 
> coz this is the normal output:
> 
> ```
> 0164:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007FFFFE64FE10
> 0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 0000145E1D537A90, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
> 0024:fixme:wbemprox:client_security_Release 00000002419BFD50
> 0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
> 0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
> 0024:fixme:ntdll:EtwEventRegister ({f72b578f-cae9-556a-01dc-b94f14b3cbd9}, 000000013F001100, 000000013F05B018, 000000013F05B038) stub.
> 0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504BE, 13) stub
> 0024:fixme:ntdll:EtwEventRegister ({66f0a0b9-f747-5080-bdb9-4974c990ecd2}, 000000013F001100, 000000013F05B050, 000000013F05B070) stub.
> 0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504DC, 19) stub
> 0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
> 0188:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
> 0188:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 0000145D60BFDB50, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
> 0188:fixme:wbemprox:client_security_Release 00000002419BFD50
> 0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
> 0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
> 0188:fixme:wbemprox:enum_class_object_Next timeout not supported
> 0094:fixme:mountmgr:query_property Faking StorageDeviceProperty data
> 0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
> 0174:fixme:iphlpapi:NotifyAddrChange (Handle 0x145d5cbe0410, overlapped 0x145d5cbe0418): stub
> 0094:fixme:mountmgr:query_property Faking StorageDeviceProperty data
> 0094:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
> 0024:fixme:ntdll:EtwEventRegister ({b77d8a36-ef0c-4976-8d22-08f986f56cfb}, 0000000138879800, 00000001393101A0, 00000001393AFA88) stub.
> 0194:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 0000145D5C6FFE10
> dbus[95]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
> This is normally a bug in some application using the D-Bus library.
> 
>   D-Bus not built with -rdynamic so unable to print a backtrace
> wine: Assertion failed at address 00001540AE492A7C (thread 0094), starting debugger...
> 0174:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
> 0174:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
> 0170:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x145d5cb5fa18.
> 0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 0000145D615B1030, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
> 0024:fixme:wbemprox:client_security_Release 00000002419BFD50
> 0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
> 0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
> 0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
> 0024:fixme:ntdll:EtwEventRegister ({35167f8e-49b2-4b96-ab86-435b59336b5e}, 0000145E24B736D0, 0000000000003D03, 0000145D3463FAA0) stub.
> 0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000145CE0AA7020, 65) stub
> ```
> 
> so at this point you should be able to connect. Do me a favor: alter the ports in ../server//VRisingServer_Data/StreamingAssets/Settings/ServerHostSettings.json
> 
> so for example
> 
> ```
>   "Port": 9886,
>   "QueryPort": 9887,
> ```
> 
> and restart your docker with
> 
> ```
> -p 9886:9886
> -p 9887:9887
> ```
> 
> Then portforward these ports on your firewall to your dockerhost.

II changed the ports and still no luck
