### ISSUE TITLE
Hosting Server in virtualized environment (kvm in proxmox)

### ISSUE THREAD

**Issue by tardar** [TrueOsiris/docker-vrising#49]
My container logs in portainer tell me this:

`wine: configuration in L"/root/.wine" has been updated.
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=16777216"
    "memorysetup-job-temp-allocator-block-size=33554432"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-allocator-temp-initial-block-size-main=262144"
    "memorysetup-allocator-temp-initial-block-size-worker=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
0024:fixme:combase:RoGetActivationFactory (L"Windows.System.DispatcherQueue", {00000035-0000-0000-c000-000000000046}, 000000000020F208): semi-stub
0024:err:combase:RoGetActivationFactory Failed to find library for L"Windows.System.DispatcherQueue"
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00000000632A7AC0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:iphlpapi:NotifyAddrChange (Handle 0x75057dd60218, overlapped 0x75057dd60220): stub
dbus[120]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00007A9F86A9AA7C (thread 0090), starting debugger...
0178:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
0178:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007505CD6B63F0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0178:fixme:wbemprox:client_security_Release 00000002419BFD50
0178:fixme:wbemprox:enum_class_object_Next timeout not supported
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
014c:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x7505ccfef9f8.
0024:fixme:ntdll:EtwEventRegister ({b77d8a36-ef0c-4976-8d22-08f986f56cfb}, 000000013898BFE0, 00000001394223A0, 00000001394DAE48) stub.
0188:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007505A51EFE10
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0024:fixme:heap:RtlSetHeapInformation 00000000006E0000 0 000000000020D840 4 stub
01b4:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007505A47BFE10
0024:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 000000000020CBC8, 00007504CF69ABF0, 000000000020CBC0, 000000000020CB60
0024:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 000000000020CBC8, 00007504CF69ABF0, 000000000020CBC0, 000000000020CB60
0104:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
0104:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007504CF6AA9E0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:file:NtLockFile I/O completion on lock not implemented yet
01c0:fixme:file:NtLockFile I/O completion on lock not implemented yet
01c0:fixme:process:SetProcessShutdownParameters (00000100, 00000001): partial stub.
0104:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
0104:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)
0104:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
0104:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0150:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering`

Unfortunately i can't connect to the server - ports are forwarded in firewall and the ports are open to the outside of the world (checked with nmap).
The server doesn#t have a GPU but - it should work, too right ?

Thanks for checkin and helpin alot

Tardar

**Comment by lockenkop** [comment]
I'm currently trying to setup this image in a lxc container with proxmox aswell, on an alpine docker lxc from here https://helper-scripts.com/scripts?id=hwyt88cnb31m7fy
My Behaviour is similar to yours. Cant connect. 

Your logs seem incomplete though, its not the full container run. There should be some steam cli at the start:

'''
Setting timezone to Europe/Berlin

Current default time zone: 'Europe/Berlin'
Local time is now:      Fri May 10 18:41:44 CEST 2024.
Universal Time is now:  Fri May 10 16:41:44 UTC 2024.

usermod: user 'docker' does not exist
 
Updating V-Rising Dedicated Server files...
 
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1714855729
-- type 'quit' to exit --
Loading Steam API...OK
"@sSteamCmdForcePlatformType" = "windows"

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.28 (5242880 / 1841345579)
 Update state (0x5) verifying install, progress: 19.85 (365419665 / 1841345579)
 Update state (0x5) verifying install, progress: 43.85 (807431738 / 1841345579)
 Update state (0x5) verifying install, progress: 68.76 (1266199568 / 1841345579)
 Update state (0x5) verifying install, progress: 93.56 (1722776823 / 1841345579)
Success! App '1829350' fully installed.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
steam_appid: 1604030
 
avx
avx
avx
avx
avx
avx
avx
avx
avx
avx
avx
avx
avx
avx
avx
avx
 
Starting V Rising Dedicated Server with name MerseRising
Trying to remove /tmp/.X0-lock
 
Starting Xvfb
Launching wine64 V Rising
 
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=16777216"
    "memorysetup-job-temp-allocator-block-size=33554432"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-allocator-temp-initial-block-size-main=262144"
    "memorysetup-allocator-temp-initial-block-size-worker=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
0024:fixme:combase:RoGetActivationFactory (L"Windows.System.DispatcherQueue", {00000035-0000-0000-c000-000000000046}, 000000000020F208): semi-stub
0024:err:combase:RoGetActivationFactory Failed to find library for L"Windows.System.DispatcherQueue"
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00000000640B22D0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:iphlpapi:NotifyAddrChange (Handle 0x7202e9760218, overlapped 0x7202e9760220): stub
01ec:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
01ec:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 0000000067E577A0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
01ec:fixme:wbemprox:client_security_Release 00000002419BFD50
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
01ec:fixme:wbemprox:enum_class_object_Next timeout not supported
0060:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0060:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0024:fixme:ntdll:EtwEventRegister ({b77d8a36-ef0c-4976-8d22-08f986f56cfb}, 000000013898BFE0, 00000001394223A0, 00000001394DAE48) stub.
01f8:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000072033ABEFE10
dbus[69]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 0000749179338A7C (thread 0060), starting debugger...
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01cc:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x7203443ef9f8.
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
01d0:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
    "MaxConnectionsPerIp": 20,
    "MaxConnections": 20,
    "ExperimentalCommandsEnabled": false
  }
}
Setting breakpad minidump AppID = 1604030
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
PlatformSystemBase -  Setting Product and Modir: V Rising
PlatformSystemBase -  Server App ID: 1604030
PlatformSystemBase - Steam GameServer Initialized!
/start.sh: line 65:    58 Killed                  DISPLAY=:0.0 wine64 /mnt/vrising/server/VRisingServer.exe -persistentDataPath $p -serverName "$SERVERNAME" -saveName "$WORLDNAME" -logFile "$p/VRisingServer.log" "$game_port" "$query_port" 2>&1
00f8:fixme:file:CancelSynchronousIo (000000000000006C): stub
00f8:fixme:file:CancelSynchronousIo (000000000000006C): stub
00f8:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000021FD40
0214:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000021FD40
'''

**Comment by TrueOsiris** [comment]
Closing this as per comment of @lockenkop 
Yes, it should of course work without a gpu.
Also: hard to read that log without linebreaks.
