### ISSUE TITLE
Cannot change the description

### ISSUE THREAD

**Issue by MandoDB** [TrueOsiris/docker-vrising#50]
Hi ! I cant change the description of the server. I tried in the ServerHostSettings.json but didnt work. How can i fix that ?

**Comment by Diyagi** [comment]
You can set the env var `VR_DESCRIPTION`, it should work as it overrides everything else.

**Comment by TrueOsiris** [comment]
Adding this to the README.md. Thanks

**Comment by TrueOsiris** [comment]
Reverting to previous version.
You can simply alter the Description= line in ServerHostSettings.json in /persistentdata and restart the server.
