### ISSUE TITLE
Cannot connect to server anymore

### ISSUE THREAD

**Issue by codevski** [TrueOsiris/docker-vrising#51]
Env: Docker latest

Not able to connect to the server anymore, nothing has changed on my end this is in the logs:

```
0e4:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000021FD40

Unity.Entities.ComponentSystemGroup:UpdateAllSystems()

Unity.Entities.SystemBase:Update()

Unity.Entities.ComponentSystemGroup:UpdateAllSystems()

Unity.Entities.InitializationSystemGroup:OnUpdate()

Unity.Entities.SystemBase:Update()

[ line 2153288]

[476:488:20240511,134826.216:ERROR filesystem_win.cc:129] GetFileAttributes C:\users\root\AppData\LocalLow\Stunlock Studios\VRisingServer\backtrace\crashpad\attachments\8d3e62f4-27e3-479c-8f7e-355537bf6261: File not found. (2)

[476:488:20240511,134826.286:WARNING minidump_to_upload_parameters.cc:32] duplicate key guid, discarding value 8cbc8871fbc792ef960c09c6b080b7dd85486c0b

01e8:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

0218:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000021FD40

[476:488:20240511,134828.926:ERROR http_transport_win.cc:388] HTTP status 403

01e0:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000021FD70
```

Server is visible, after server starting up (232/239 etc) it stops and not able to connect with timeout I think it crashes

**Comment by sreckcep** [comment]
I am experiencing the same problem. Wiped out saves, configuration, and it still crashes with that same error.

**Comment by Mjolinir** [comment]
Same issue as well:

`0024:fixme:combase:RoGetActivationFactory (L"Windows.System.DispatcherQueue", {00000035-0000-0000-c000-000000000046}, 000000000020F208): semi-stub
0024:err:combase:RoGetActivationFactory Failed to find library for L"Windows.System.DispatcherQueue"
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0024:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000020F400
00d4:fixme:file:CancelSynchronousIo (000000000000006C): stub
[Physics::Module] Initialized MultithreadedJobDispatcher with 3 workers.
Failed to create batch mode window: Success.

00d4:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000021FD40
0144:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000021FD40`

**Comment by shlau** [comment]
Some people have had success using xvfb, so possible solution:

Add a step to install xvbf in the docker file
`apt-get install -y xvfb && \`

and replace the last 2 lines in start.sh with 
` xvfb-run --auto-servernum --server-args='-screen 0 640x480x24:32' wine64 /mnt/vrising/server/VRisingServer.exe -persistentDataPath $p -serverName "$SERVERNAME" -saveName "$WORLDNAME" -logFile "$p/VRisingServer.log" "$game_port" "$query_port" 2>&1
/usr/bin/tail -f /mnt/vrising/persistentdata/VRisingServer.log`

**Comment by TrueOsiris** [comment]
testing this solution

**Comment by TrueOsiris** [comment]
created trueosiris/vrising:display as a separate image
