### ISSUE TITLE
Unable to launch server (winsock error)

### ISSUE THREAD

**Issue by firedfromlife** [TrueOsiris/docker-vrising#56]
I can't seem to get the server running at all.
I have tried using the image tagged with winehq, same problem.
Any assistance would be greatly appreciated.

I am running this using the following yaml file in portainer.

```
services:
  vrising:
    image: trueosiris/vrising
    environment:
      - TZ=America/Phoenix
      - SERVERNAME="P Rising"
      - WORLDNAME="world1_prising"
      
    volumes:
      - /nfs/vrising/server:/mnt/vrising/server
      - /nfs/vrising/persistentdata:/mnt/vrising/persistentdata
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
    restart: unless-stopped
    network_mode: bridge
```

The logs are as follows:

>  "@sSteamCmdForcePlatformType" = "windows"
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.11 (2097152 / 1841345579)
 Update state (0x5) verifying install, progress: 43.04 (792506919 / 1841345579)
 Update state (0x5) verifying install, progress: 84.63 (1558300701 / 1841345579)
 Update state (0x61) downloading, progress: 10.36 (13631488 / 131584272)
 Update state (0x61) downloading, progress: 100.00 (131584272 / 131584272)
Success! App '1829350' fully installed.
steam_appid: 1604030
AVX or AVX2 not supported; Check if unsupported VRisingServer_Data/Plugins/x86_64/lib_burst_generated.dll exists
Changing VRisingServer_Data/Plugins/x86_64/lib_burst_generated.dll as attempt to fix issues...
Creating /mnt/vrising/persistentdata/20240513-1633-VRisingServer.log
Starting V Rising Dedicated Server with name "P Rising"
Trying to remove /tmp/.X0-lock
Starting Xvfb
Launching wine64 V Rising
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=16777216"
    "memorysetup-job-temp-allocator-block-size=33554432"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-allocator-temp-initial-block-size-main=262144"
    "memorysetup-allocator-temp-initial-block-size-worker=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
0024:fixme:combase:RoGetActivationFactory (L"Windows.System.DispatcherQueue", {00000035-0000-0000-c000-000000000046}, 000000000020F208): semi-stub
0024:err:combase:RoGetActivationFactory Failed to find library for L"Windows.System.DispatcherQueue"
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
[Physics::Module] Initialized MultithreadedJobDispatcher with 7 workers.
Initialize engine version: 2022.3.23f1 (dbb3f7c5b5c6)
[Subsystems] Discovering subsystems at path Z:/mnt/vrising/server/VRisingServer_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0; jobified=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
There is no texture data available to upload.
Microsoft Media Foundation video decoding to texture disabled: graphics device is Null, only Direct3D 11 and Direct3D 12 (only on desktop) are supported for hardware-accelerated video decoding.
There is no texture data available to upload.
There is no texture data available to upload.
There is no texture data available to upload.
There is no texture data available to upload.
UnloadTime: 1.425200 ms
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00000000638407C0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0184:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007FFFFE31FE10
013c:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
013c:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)
AutomaticWorldBootstrap.Initialize
Set a new SaveFileManager 'Stunlock.Platform.PC.SaveFileManagerPC'
Loaded GeneralGameSettings:
{
  "JobWorkerCount": 4,
  "EnableDebugging": true,
  "SteamLogLevel": 5,
  "SteamCaptureAPILogs": false,
  "SteamCaptureNetworkingLogs": false
}
Bootstrap - Boot Time: 2024-05-13 23:33:25 UTC, Version: VRisingServer v1.0.1.79323 b31 (2024-05-09 14:42 UTC) (Release)
DEDICATED_SERVER defined.
UNITY_ASSERTIONS defined.
UNITY_DOTS_DEBUG defined.
Burst is Disabled
System Information:
processorFrequency: 3399
deviceModel: Wine (The Wine Project)
operatingSystem: Windows 7  (6.1.0) 64bit
processorType: QEMU Virtual CPU version 2.5+
processorCount: 8
systemMemorySize: 33070
graphicsDeviceName: Null Device
graphicsDeviceType: Null
graphicsDeviceVendor: Unity Technologies
graphicsDeviceVendorID: 0
graphicsDeviceVersion: NULL 1.0 [1.0]
graphicsMemorySize: 128
graphicsMultiThreaded: False
graphicsShaderLevel: 30
maxTextureSize: 4096
CPU Score: 10197 (WOW)
Bootstrapping World: Default World
PlatformSystemBase - - Entering OnCreate!
PersistentDataPath: /mnt/vrising/persistentdata root: /mnt/vrising/persistentdata\Saves
Loaded VersionDataSettings:
{
  "NetworkVersion": 16,
  "PersistenceVersion": 3
}
PersistenceVersionOverride value found from VersionDataSettings: 3
Persistence Version initialized as: 3
ArgumentException: Illegal characters in path.
  at System.IO.Path.Combine (System.String path1, System.String path2) [0x00000] in <00000000000000000000000000000000>:0 
  at ProjectM.SettingsManager.VerifyServerSettings (System.Boolean silentInitialize) [0x00000] in <00000000000000000000000000000000>:0 
  at ProjectM.SettingsManager.get_ServerHostSettings () [0x00000] in <00000000000000000000000000000000>:0 
  at ProjectM.Auth.PlatformSystemBase.OnCreate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemBase.CreateInstance (Unity.Entities.World world) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.World.AddSystem_OnCreate_Internal (Unity.Entities.ComponentSystemBase system) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.World.GetOrCreateSystemsAndLogException (Unity.Collections.NativeList`1[T] types, System.Int32 typesCount, Unity.Collections.AllocatorManager+AllocatorHandle allocator) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.World.GetOrCreateSystemsAndLogException (Unity.Collections.NativeList`1[T] types, Unity.Collections.AllocatorManager+AllocatorHandle allocator) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Core.WorldBootstrapUtilities.AddSystemsToWorld (Unity.Entities.World world, Stunlock.Core.WorldBootstrap worldConfig, Stunlock.Core.WorldSystemConfig worldSystemConfig) [0x00000] in <00000000000000000000000000000000>:0 
  at ProjectM.Bootstrap.Unity.Entities.ICustomBootstrap.Initialize (System.String defaultWorldName) [0x00000] in <00000000000000000000000000000000>:0 
  at Stunlock.Core.WorldBootstrapUtilities.InitializeDefaultWorldWithBootstrap (System.String defaultWorldName) [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Unity.Entities.World:GetOrCreateSystemsAndLogException(NativeList`1, Int32, AllocatorHandle)
Unity.Entities.World:GetOrCreateSystemsAndLogException(NativeList`1, AllocatorHandle)
Stunlock.Core.WorldBootstrapUtilities:AddSystemsToWorld(World, WorldBootstrap, WorldSystemConfig)
ProjectM.Bootstrap:Unity.Entities.ICustomBootstrap.Initialize(String)
Stunlock.Core.WorldBootstrapUtilities:InitializeDefaultWorldWithBootstrap(String)
EOSPlatformSystem - Entering OnCreate!
EOSPlatformSystem - Skipping EOS initialization - EOS features disabled!
NullReferenceException: Object reference not set to an instance of an object.
  at ProjectM.GameBootstrap.Start () [0x00000] in <00000000000000000000000000000000>:0 
013c:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
013c:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)
013c:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
013c:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)

**Comment by TrueOsiris** [comment]
Do me a favor and try trueosiris/vrising:2.0
That one was definitely working on multiple systems.

**Comment by firedfromlife** [comment]
> Do me a favor and try trueosiris/vrising:2.0 That one was definitely working on multiple systems.

Results of that attempt, trimmed to relevant errors.
> 0024:fixme:combase:RoGetActivationFactory (L"Windows.System.DispatcherQueue", {00000035-0000-0000-c000-000000000046}, 000000000020F208): semi-stub
0024:err:combase:RoGetActivationFactory Failed to find library for L"Windows.System.DispatcherQueue"
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00000000638457A0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
0024:fixme:wbemprox:client_security_Release 00000002419BFD50
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
0178:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007FFFFE31FE10

**Comment by TrueOsiris** [comment]
I'm reopening issue 47 and closing this one. same issue.
https://github.com/TrueOsiris/docker-vrising/issues/47
