### ISSUE TITLE
SaveName in ServerHostSettings.json is ignored

### ISSUE THREAD

**Issue by ScarlettHoefler** [TrueOsiris/docker-vrising#60]
Setting your save name in ServerHostSettings.json doesn't seem to work.

I'm assuming the issue comes from start.sh always setting the world name if you haven't set an environment variable:

```sh
if [ -z "$WORLDNAME" ]; then
	WORLDNAME="world1"
fi
```

Which later gets passed as...

```sh
-saveName "$WORLDNAME"
```

And so it's always defaulting to `world1` unless you set a different one as an environment variable, thus meaning the JSON file is ignored entirely.

I worked around this by just using a new environment variable

**Comment by TrueOsiris** [comment]
fixed
```
override_savename=""
if [ ! -z "$WORLDNAME" ]; then
	override_savename="-saveName $WORLDNAME"
fi

...

v() {
	DISPLAY=:0.0 wine64 /mnt/vrising/server/VRisingServer.exe -persistentDataPath $p -serverName "$SERVERNAME" $override_savename -logFile "$p/$logfile" "$game_port" "$query_port" 2>&1 &
}
v
```
