### ISSUE TITLE
Public IPV4 Showing 0.0.0.0 

### ISSUE THREAD

**Issue by Killerherts** [TrueOsiris/docker-vrising#64]
Are we needing to bind directly to our public ip address in order for the ipv4 address to be displayed for processed correctly by the game server? 
How we are doing things now it is binding to 0.0.0.0 and when I am at the social screen while in server the address is displayed as 0.0.0.0. 
I have moved my vm several times and when my local address changed this broke the continue button in game and requires you to use the server browser or direct connect to connect. 

![image](https://github.com/TrueOsiris/docker-vrising/assets/20962973/393c9047-91d4-4219-93a1-73168001504b)

I have tried using host mode, but then wine doesn't see our listening address and thinks our server is not running.

**Comment by TrueOsiris** [comment]
I'm not seeing this section in the social screen at all. 

Secondly, how important is it to see the server ip, while you're already on it? 
Are your friends connecting on direct ip and are you not publishing it in the server list?

**Comment by Killerherts** [comment]
> I'm not seeing this section in the social screen at all.
 
So it was the system screen I was incorrect. It's was mostly an observation as in the traditional client your public IP address is listed there. 


> Secondly, how important is it to see the server ip, while you're already on it? Are your friends connecting on direct ip and are you not publishing it in the server list?

I was just thinking of people who don't know any better and would share the 0.0.0.0 from that screen with their friends without knowing it's a binding address.

For the record my server is published to the lists just fine and if your know my public or local you can connect direct this was more of an outlier observation and was curious if anyone knew why.

**Comment by Killerherts** [comment]
Binding to the local address of the host fixed this. 
```
ports
  - 192.168.1.101:27015:27015
  - 192.168.1.101:27016:27016
 
```

We currently don't have the rcon port in the compose example commented or something.
