### ISSUE TITLE
Can't see game in Server list on VRising

### ISSUE THREAD

**Issue by pzohner** [TrueOsiris/docker-vrising#66]
![image](https://github.com/TrueOsiris/docker-vrising/assets/19269295/49458c58-7797-431c-8587-d3ae68889aec)
Does 'Failed to Initialize SteamNetworking' have anything to do with that?

I have opened up more ports as someone mentioned you need more ports opened in order for steam to see the game. 
heres my compose file:
![image](https://github.com/TrueOsiris/docker-vrising/assets/19269295/a01e646c-8bce-4ed0-8436-7d772fdd8cc0)

Am I missing anything else? All those ports are also forwarded on my router to my server.

Thanks so much for giving us a way to host V Rising on something other than windows :D

**Comment by Killerherts** [comment]
You only need to do
```
 27015:27015
 27016:27016
```
Also you can't find the multiple ports to the same one or multiple times. 


You need to add the queryport and gameport to your env section
```
environment:
  -GAMEPORT=27015
  -QUERYPORT=27016
```
You will also need to forward those ports on your router/firewall to the appropriate local address. Much of this is part of the vrising hosting documents.

**Comment by TrueOsiris** [comment]
A normal docker installation shouldn't even be able to start your container with that config.
if you change the ports to 27015, 27016, you should spin up the container, wait 10 minutes, and stop it.
Then you can alter ServerHostSettings.json (in your /data folder on your host) and also change the ports there. 
And then start it.
Then, on your firewall, you need to forward your incoming traffic on those ports to your dockerhost's internal ip (also on those ports)

The explanation is in the readme.md
