### ISSUE TITLE
do we need to recreate the instance

### ISSUE THREAD

**Issue by haunter81** [TrueOsiris/docker-vrising#72]
Greetings all!

i had got the docker instance before the v.1 release . Should i create a new instance , or the one i got is updated??(and how can i check it?)

thanks in advance

**Comment by Vidski** [comment]
As far as I know, V-Rising v1.0 dropped support for saves made in early access. Your best bet is to create a new save. To download the latest image, simply set the image version in your docker compose to latest and run docker pull.
