### ISSUE TITLE
Arbitrary ports

### ISSUE THREAD

**Issue by mckamyk** [TrueOsiris/docker-vrising#75]
Can we publish a server on Steam with any port we want set to `Port` and `QueryPort`? or are only  9876/9877 and 27017/27018 allowed?

**Comment by DOGE28** [comment]
You simply change the ports in the docker-compose file (or the docker command) as well as in ServerHostSettings.json.

In the docker-compose file/docker command, you only change the first port, for example 9999:9876. The port number on the right is the one that docker uses internally to expose the container to your local network. Your local network is then mapped to the port on the left and is the one you and your friends can use to connect with.

**Comment by TrueOsiris** [comment]
You can change it to anything. Change the docker ports & also adapt them in the serverhostsettings.json.
