### ISSUE TITLE
Running on debian without sound card?

### ISSUE THREAD

**Issue by MMM-Jasmin** [TrueOsiris/docker-vrising#8]
thanks for the effort first of all!
I am trying to let it run on my nas at home which is running omv6 (so debian)
Sadly the game tries to get the audio card and seems to crash.. 
Any ideas?

> Downloading and installing .NET SDK 6.0.300 and core runtime...
>
>
>Updating V-Rising Dedicated Server files...
> 
>WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
>Redirecting stderr to '/root/Steam/logs/stderr.txt'
>[  0%] Checking for available updates...
>[----] Verifying installation...
>Steam Console Client (c) Valve Corporation - version 1653101151
>-- type 'quit' to exit --
>Loading Steam API...OK
>
>Connecting anonymously to Steam Public...OK
>Waiting for client config...OK
>Waiting for user info...OK
>Success! App '1829350' already up to date.
>steam_appid: 1604030
>
>Starting V Rising Dedicated Server with name NilzWorld
>SteamAppId set to 
>Starting Xvfb and wine64 ...
> 
>0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
>ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
>ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
>ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
>ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
>ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
>ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
>ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
>ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
>ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
>ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
>ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
>ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
>ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
>ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
>ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
>ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
>0188:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007FFFFF0CFE10
>0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007F40BC0C7F50, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
>0024:fixme:wbemprox:client_security_Release 00000002419BFD50
>0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
>0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
>0024:fixme:keyboard:X11DRV_GetKeyboardLayout couldn't return keyboard layout for thread 0050
>0024:fixme:keyboard:X11DRV_GetKeyboardLayout couldn't return keyboard layout for thread 0050
>0024:fixme:ntdll:EtwEventRegister ({f72b578f-cae9-556a-01dc-b94f14b3cbd9}, 000000013F001100, 000000013F05B018, 000000013F05B038) stub.
>0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504BE, 13) stub
>0024:fixme:ntdll:EtwEventRegister ({66f0a0b9-f747-5080-bdb9-4974c990ecd2}, 000000013F001100, 000000013F05B050, 000000013F05B070) stub.
>0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504DC, 19) stub
>0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. >Usually, you can find it in the winbind package of your distribution.
>01ac:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
>01ac:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007F40BCC2A0C0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
>01ac:fixme:wbemprox:client_security_Release 00000002419BFD50
>0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
>0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
>01ac:fixme:wbemprox:enum_class_object_Next timeout not supported
>0060:fixme:mountmgr:query_property Faking StorageDeviceProperty data
>0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
>0060:fixme:mountmgr:query_property Faking StorageDeviceProperty data
>0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
>0024:fixme:ntdll:EtwEventRegister ({b77d8a36-ef0c-4976-8d22-08f986f56cfb}, 0000000138879800, 00000001393101A0, 00000001393AFA88) stub.
>01b8:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007F40B963FE10
>dbus[50]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
>This is normally a bug in some application using the D-Bus library.
>
>  D-Bus not built with -rdynamic so unable to print a backtrace
>wine: Assertion failed at address 00007F09269CCA7C (thread 0060), starting debugger...
>0198:fixme:iphlpapi:NotifyAddrChange (Handle 0x7f4072040410, overlapped 0x7f4072040418): stub
>0198:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
>0198:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
>0194:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x7f412824fa18.
>0024:fixme:wbemprox:client_security_SetBlanket 00000002419BFD50, 00007F40BD5D8B10, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
>0024:fixme:wbemprox:client_security_Release 00000002419BFD50
>0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
>0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
>0024:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
>0024:fixme:ntdll:EtwEventRegister ({35167f8e-49b2-4b96-ab86-435b59336b5e}, 00007F41802E36D0, 0000000000003CF3, 00007F40B9A4A560) stub.
>0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00007F4070649C60, 65) stub

**Comment by Chapapa1** [comment]
try joining the server, i have a similar log file, but the server runs fine

**Comment by MMM-Jasmin** [comment]
ohh this seems not to be an issue.. sorry

**Comment by MMM-Jasmin** [comment]
@Chapapa1 my problem was the port change i did as well..
but now I have to forward other ports on my router.. which leads to the server not showing in the server browser and I can just connect directly to it.
