### ISSUE TITLE
PS5 Server No EOS Session error.

### ISSUE THREAD

**Issue by miimikko** [TrueOsiris/docker-vrising#82]
I'm trying to use the PS5 version of the server and when direct connecting I get asked the server password as expected, however after inputting it I get the following errors:

```
Client connected with platform User ID xxxxxxxxxxxxx
NetConnection '{Lidgren 192.168.10.1:54166}' connection was denied. Message: 'Server has no EOS Session' Version: 16 PlatformId: xxxxxxxxxxxxx
Received unhandled library message Acknowledge from 192.168.10.1:54166
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Stunlock.Network.Lidgren.LidgrenServer:ReadMessages()
ProjectM.ServerBootstrapSystem:OnUpdate()
Unity.Entities.SystemBase:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.SystemBase:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.SystemBase:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.InitializationSystemGroup:OnUpdate()
Unity.Entities.SystemBase:Update()
```
Earlier in the logs I also have these lines: 

```
PlatformSystemBase - Server connected to Steam successfully!
SteamNetworking - Successfully logged in with the SteamGameServer API. SteamID: xxxxxxxxxx
EOSPlatformSystem - Entering OnCreate!
EOSPlatformSystem - Skipping EOS initialization - EOS features disabled!
```
Anyone got an idea what could be the cause of this?

**Comment by kevinf100** [comment]
Set `"ListOnEOS"` to true in `ServerHostSettings.json`.

**Comment by miimikko** [comment]
> Set `"ListOnEOS"` to true in `ServerHostSettings.json`.

Yeah tried that previously to no effect. Luckily after a couple of days I stumbled on the solution:

On line 25 of the Dockerfile there is a line commented out: `RUN apt install -y mono-complete`. Uncommented this and built again and it worked like a charm. If anyone is wondering how to run the PS5 version of the server you need to modify the start.sh script line 59 to look like this: `/usr/bin/steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir "$s" +login anonymous +app_update 1829350 -beta ce-1 validate +quit` and then build the image.
