### ISSUE TITLE
Updating V-Rising Dedicated Server files is not working

### ISSUE THREAD

**Issue by eberdt** [TrueOsiris/docker-vrising#9]
Hey, I try to install it on my root servers. But I run into the same problem again and again:

```
´2022-05-22 19:50:08 (96.3 MB/s) - 'aspnetcore-runtime-6.0.5-linux-x64.tar.gz' saved [39827854/39827854]


Updating V-Rising Dedicated Server files...
```

It runs for hours already and the size of the data or server folder is not increasing.

is there something I do completely wrong?

**Comment by mattiasghodsian** [comment]
> Hey, I try to install it on my root servers. But I run into the same problem again and again:
> 
> ```
> ´2022-05-22 19:50:08 (96.3 MB/s) - 'aspnetcore-runtime-6.0.5-linux-x64.tar.gz' saved [39827854/39827854]
> 
> 
> Updating V-Rising Dedicated Server files...
> ```
> 
> It runs for hours already and the size of the data or server folder is not increasing.
> 
> is there something I do completely wrong?

Did run with cli or compose ?

**Comment by eberdt** [comment]
compose

**Comment by eberdt** [comment]
I try it with the cli and only copy and paste the command from the README.md and I got the same result
It freezes again at ` Updating V-Rising Dedicated Server files...`

These are the current file sizes, exact the same as I have with the compose setup
```
487M    ./data/dotnet
487M    ./data
4.0K    ./server
```

**Comment by TrueOsiris** [comment]
Hi. Please do me a favor & show me your full docker log please.
+ hardware & os if possible.

**Comment by eberdt** [comment]
I add the logs: [vrising.log](https://github.com/TrueOsiris/docker-vrising/files/8751654/vrising.log)
The last root server where I test it was a: Intel Core i7-4770 with 32gb of ram with Ubuntu 20.04.2 LTS

The only problem that I miss before is `/start.sh: line 10: [: Team: binary operator expected`

When I execute the apt-get I get the following error:
```
root@18a2d2ab4e08:/# apt-get update && apt-get install -y iputils-ping
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke-Success '/usr/bin/test -e /usr/share/dbus-1/system-services/org.freedesktop.PackageKit.service && /usr/bin/test -S /var/run/dbus/system_bus_socket && /usr/bin/gdbus call --system --dest org.freedesktop.PackageKit --object-path /org/freedesktop/PackageKit --timeout 4 --method org.freedesktop.PackageKit.StateHasChanged cache-update > /dev/null; /bin/echo > /dev/null'
E: Sub-process returned an error code
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
```

to let steam run on this host system in a container is not in general a problem. There run already some container with other game server like ARK, Wreckfest and some more

**Comment by rschrader** [comment]
@eberdt did you found any workaround? I am currently facing the exact same issue.

**Comment by eberdt** [comment]
nope, nothing that works for me

**Comment by TrueOsiris** [comment]
I'm classifying this as "container cannot access the outside world".
If from within the container you cannot use `apt-get update && apt-get install -y iputils-ping` then the problem is not mine.
